"""empty message

Revision ID: 41374fd812f5
Revises: e24441cde860
Create Date: 2019-06-24 16:24:26.701509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41374fd812f5'
down_revision = 'e24441cde860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('client_login_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'client_login_status')
    # ### end Alembic commands ###
