"""empty message

Revision ID: c4bf517fddd4
Revises: 277afd83fdff
Create Date: 2019-06-19 18:22:32.478043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bf517fddd4'
down_revision = '277afd83fdff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('payment_type', sa.String(length=120), nullable=True),
    sa.Column('payment_status', sa.String(length=120), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.String(length=20), nullable=True),
    sa.Column('order_notes', sa.String(length=5000), nullable=True),
    sa.Column('order_issues', sa.String(length=5000), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
