"""empty message

Revision ID: e24441cde860
Revises: 7f00749cb4e6
Create Date: 2019-06-23 18:35:08.364332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e24441cde860'
down_revision = '7f00749cb4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_consultant', sa.String(length=120), nullable=True),
    sa.Column('service', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=5000), nullable=True),
    sa.Column('package', sa.String(length=5000), nullable=True),
    sa.Column('orders_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['orders_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('orders_id', sa.Integer(), nullable=True))
    op.add_column('client', sa.Column('service_catalog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client', 'service_catalog', ['service_catalog_id'], ['id'])
    op.create_foreign_key(None, 'client', 'orders', ['orders_id'], ['id'])
    op.add_column('orders', sa.Column('client_email', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('meeting_type', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('service_catalog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'service_catalog', ['service_catalog_id'], ['id'])
    op.drop_column('orders', 'order_number')
    op.drop_column('orders', 'assigned_consultant')
    op.drop_column('orders', 'selected_services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('selected_services', mysql.VARCHAR(length=5000), nullable=True))
    op.add_column('orders', sa.Column('assigned_consultant', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('orders', sa.Column('order_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'service_catalog_id')
    op.drop_column('orders', 'meeting_type')
    op.drop_column('orders', 'client_email')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'service_catalog_id')
    op.drop_column('client', 'orders_id')
    op.drop_table('service_catalog')
    # ### end Alembic commands ###
