"""empty message

Revision ID: eab39cbb21db
Revises: ab16261dd3d2
Create Date: 2019-06-27 16:17:35.527983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eab39cbb21db'
down_revision = 'ab16261dd3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'meeting_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('meeting_type', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
